### ISSUE TITLE
Envie aqui sua resposta

### ISSUE THREAD

**Issue by cavalcantigor** [murielmagno/tutoria-java#1]

**Comment by murielmagno** [comment]
.

**Comment by melyssaraiol** [comment]
https://github.com/melyssaraiol/tutoria-poo

**Comment by Carlosvpm** [comment]
https://github.com/Carlosvpm/oficina_java

**Comment by Nhed1** [comment]
https://github.com/Nhed1/tutoria-java-crud

**Comment by sergiopassinho** [comment]
https://github.com/sergiopassinho/atvpoo2

**Comment by Moises-Rander** [comment]
https://github.com/Moises-Rander/PraticaP2

**Comment by rmo02** [comment]
https://github.com/rmo02/CRUD-Java

**Comment by ThornHart** [comment]
https://github.com/ThornHart/tutoria_java

**Comment by danielthejoker18** [comment]
https://github.com/danielthejoker18/tutoria-java-Cad-Alunos

**Comment by cavalcantigor** [comment]
> https://github.com/melyssaraiol/tutoria-poo

Parabéns. Foi além do esperado. :)

**Comment by cavalcantigor** [comment]
> https://github.com/Carlosvpm/oficina_java

Gostei dos refactorings. Faltou finalizar a parte de Turma e Professor, mas fez um pouco da tarefa bônus.

**Comment by cavalcantigor** [comment]
> https://github.com/Nhed1/tutoria-java-crud

Fez o que foi solicitado. Parabéns.

**Comment by cavalcantigor** [comment]
> https://github.com/rmo02/CRUD-Java

Foi além e fez o bônus, mas não conseguiu fazer a relação entre turma e professor. Parabéns :)

**Comment by cavalcantigor** [comment]
> https://github.com/danielthejoker18/tutoria-java-Cad-Alunos

Foi além. Gostei do capricho com o código. O dump da base também foi legal pra saber como vc modelou o banco. Parabéns :)

**Comment by cavalcantigor** [comment]
> https://github.com/ThornHart/tutoria_java

Tá certo? Não tem nada do código da atividade 👁️

**Comment by cavalcantigor** [comment]
> https://github.com/Moises-Rander/PraticaP2

Fez além do básico. Deu uma atrapalhada na relação entre as entidades, mas nada grave. Parabéns :)
